[package]
name = "github-link-checker"
version = "0.1.0"
authors = ["m <m@marvelmathew.ca>"]

[dependencies]
string_cache = "0.1.13"
url = "0.2.37"
log = "0.3.2"

[dependencies.kuchiki]
git = "https://github.com/marvelm/kuchiki"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
